// Generated by CoffeeScript 1.3.1
(function() {
  var Chrome, Galaxy, KEY_DOWN, KEY_LEFT, KEY_RIGHT, KEY_SPACE, KEY_UP, Mass, Planet, Player, Sun, chrome, galaxy, h, key_dir, planet, planets, player, rotation, setPixel, w, _i, _len,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Mass = (function() {

    Mass.name = 'Mass';

    function Mass(x, y, radius, mass) {
      this.x = x;
      this.y = y;
      this.radius = radius;
      this.mass = mass;
    }

    Mass.prototype.safe = true;

    Mass.prototype.distance = 0;

    Mass.prototype.color = [200, 200, 200];

    Mass.prototype.markerColor = [127, 127, 127];

    Mass.prototype.physics = function(player) {
      var angle, p, pull;
      this.distance = this.distanceTo(player);
      if (this.distance < this.radius * 4) {
        if (this.distance > 0) {
          p = 1 - (Math.sin(this.distance / (this.radius * 4) * Math.PI / 2));
          pull = p * (this.radius + 100) * .01;
          angle = Math.PI / 2 - Math.atan2(this.x - player.x, this.y - player.y);
          player.velocityX += (Math.cos(angle)) * pull;
          return player.velocityY += (Math.sin(angle)) * pull;
        }
      }
    };

    Mass.prototype.draw = function(s, g) {
      var angle, dist, h2, size, w2, x, x1, x2, x3, y, y1, y2, y3;
      this.s = s;
      this.g = g;
      x = this.x - this.g.offsetX;
      y = this.y - this.g.offsetY;
      angle = Math.atan2(x, y);
      dist = Math.sqrt((Math.pow(x, 2)) + (Math.pow(y, 2)));
      angle += this.g.rotation;
      x = Math.cos(angle) * dist;
      y = Math.sin(angle) * dist;
      size = this.radius * 2;
      w2 = this.g.w / 2;
      h2 = this.g.h / 2;
      if ((-w2 - this.radius < x && x < w2 + this.radius) && (-h2 - this.radius < y && y < h / 2 + this.radius)) {
        x += w2;
        y += h2;
        this.s.noStroke();
        this.s.fill(this.color[0], this.color[1], this.color[2]);
        return this.s.ellipse(x, y, size, size);
      } else {
        angle = Math.PI / 2 - Math.atan2(x, y);
        dist = this.distance;
        if ((Math.abs(x)) > w2) {
          dist = Math.abs(w2 / Math.cos(angle));
          x = (Math.cos(angle)) * dist;
          y = (Math.sin(angle)) * dist;
        }
        if ((Math.abs(y)) > h2) {
          dist = Math.abs(h2 / Math.sin(angle));
          x = (Math.cos(angle)) * dist;
          y = (Math.sin(angle)) * dist;
        }
        x += w2;
        y += h2;
        this.s.strokeWeight(2);
        this.s.stroke(this.markerColor[0], this.markerColor[1], this.markerColor[2], 222);
        this.s.noFill();
        x1 = (Math.cos(angle + .01)) * (dist - 20) + w2;
        y1 = (Math.sin(angle + .01)) * (dist - 20) + h2;
        x2 = (Math.cos(angle)) * (dist - 5) + w2;
        y2 = (Math.sin(angle)) * (dist - 5) + h2;
        x3 = (Math.cos(angle - .01)) * (dist - 20) + w2;
        y3 = (Math.sin(angle - .01)) * (dist - 20) + h2;
        this.s.beginShape();
        this.s.vertex(x1, y1);
        this.s.vertex(x2, y2);
        this.s.vertex(x3, y3);
        return this.s.endShape();
      }
    };

    Mass.prototype.distanceTo = function(player) {
      return (Math.sqrt((Math.pow(this.x - player.x, 2)) + (Math.pow(this.y - player.y, 2)))) - this.radius;
    };

    return Mass;

  })();

  Planet = (function(_super) {

    __extends(Planet, _super);

    Planet.name = 'Planet';

    function Planet(x, y, radius) {
      this.x = x;
      this.y = y;
      this.radius = radius;
    }

    Planet.prototype.setup = function() {
      var lightness;
      lightness = Math.random() * 50;
      this.color = [Math.random() * lightness + 200, Math.random() * lightness + 200, Math.random() * lightness + 200];
      return this;
    };

    Planet.prototype.color = [255, 255, 255];

    Planet.prototype.markerColor = [0, 255, 0];

    return Planet;

  })(Mass);

  Sun = (function(_super) {

    __extends(Sun, _super);

    Sun.name = 'Sun';

    function Sun(x, y, radius) {
      this.x = x;
      this.y = y;
      this.radius = radius;
    }

    Sun.prototype.setup = function() {
      return this;
    };

    Sun.prototype.safe = false;

    Sun.prototype.color = [255, 200, 50];

    Sun.prototype.markerColor = [255, 0, 0];

    Sun.prototype.draw = function(s, g) {
      this.s = s;
      this.g = g;
      return Sun.__super__.draw.call(this, this.s, this.g);
    };

    return Sun;

  })(Mass);

  /* @pjs preload="images/standing.png"; */;


  /* @pjs preload="images/walking.png"; */;


  /* @pjs preload="images/squatting.png"; */;


  /* @pjs preload="images/flying.png"; */;


  Player = (function() {

    Player.name = 'Player';

    function Player() {
      var cb,
        _this = this;
      this.direction = this.DIR_RIGHT;
      this.currentImage = this.IMG_STANDING;
      this.walkingImage = this.IMG_WALKING;
      cb = function() {
        return _this.switchWalk();
      };
      setInterval(cb, 200);
    }

    Player.prototype.x = 0;

    Player.prototype.y = 0;

    Player.prototype.width = 20;

    Player.prototype.height = 25;

    Player.prototype.velocityX = 0;

    Player.prototype.velocityY = 0;

    Player.prototype.nearestPlanet = false;

    Player.prototype.jumping = false;

    Player.prototype.jumpVelocity = 0;

    Player.prototype.maxJump = 40;

    Player.prototype.minJump = 10;

    Player.prototype.maxSpeed = 3;

    Player.prototype.onGround = false;

    Player.prototype.walking = false;

    Player.prototype.DIR_RIGHT = "right";

    Player.prototype.DIR_LEFT = "left";

    Player.prototype.IMG_STANDING = "standing";

    Player.prototype.IMG_WALKING = "walking";

    Player.prototype.IMG_SQUATTING = "squatting";

    Player.prototype.IMG_FLYING = "flying";

    Player.prototype.walkingImage = "";

    Player.prototype.currentImage = "";

    Player.prototype.lastImageChange = 0;

    Player.prototype.accel = function(angle, force, cap) {
      this.velocityX += (Math.cos(angle)) * force;
      this.velocityY += (Math.sin(angle)) * force;
      if (cap && Math.sqrt((Math.pow(this.velocityX, 2)) + (Math.pow(this.velocityY, 2)) > this.maxSpeed)) {
        angle = Math.PI / 2 - Math.atan2(this.velocityX, this.velocityY);
        this.velocityX = (Math.cos(angle)) * this.maxSpeed;
        return this.velocityY = (Math.sin(angle)) * this.maxSpeed;
      }
    };

    Player.prototype.calculatePhysics = function(planets) {
      var nearPlanet, og, planet, _fn, _i, _len,
        _this = this;
      og = this.onGround;
      this.onGround = false;
      nearPlanet = false;
      _fn = function(planet) {
        var angle, dist;
        if (!og || planet.distance < 20) {
          planet.physics(_this);
        }
        dist = planet.distance;
        if (dist < planet.radius) {
          nearPlanet = true;
        }
        if (dist < 10) {
          _this.onGround = true;
          _this.velocityX *= .99;
          _this.velocityY *= .99;
          if (dist <= 0) {
            angle = Math.PI / 2 - Math.atan2(planet.x - _this.x, planet.y - _this.y);
            _this.x = planet.x - (Math.cos(angle)) * planet.radius;
            _this.y = planet.y - (Math.sin(angle)) * planet.radius;
          }
          if (dist < 5 && !_this.walking) {
            _this.velocityX *= 0.5;
            return _this.velocityY *= 0.5;
          }
        }
      };
      for (_i = 0, _len = planets.length; _i < _len; _i++) {
        planet = planets[_i];
        _fn(planet);
      }
      if (nearPlanet) {
        this.velocityX *= .99;
        this.velocityY *= .99;
      }
      if (!this.onGround) {
        this.walking = false;
      }
      return this;
    };

    Player.prototype.move = function() {
      var d, t;
      this.x += this.velocityX;
      this.y += this.velocityY;
      d = new Date();
      t = d.getTime();
      if (this.onGround && !this.jumping) {
        if (Math.abs(this.velocityX) + Math.abs(this.velocityY) > 0.1) {
          this.currentImage = this.walkingImage;
        } else {
          this.currentImage = this.IMG_STANDING;
        }
      } else {
        if (this.jumping) {
          this.currentImage = this.IMG_SQUATTING;
        } else {
          this.currentImage = this.IMG_FLYING;
        }
      }
      return this;
    };

    Player.prototype.switchWalk = function() {
      if (this.walkingImage !== this.IMG_WALKING) {
        return this.walkingImage = this.IMG_WALKING;
      } else {
        return this.walkingImage = this.IMG_STANDING;
      }
    };

    Player.prototype.findNearestPlanet = function(planets, log) {
      var nearestDistance, planet, _fn, _i, _len,
        _this = this;
      this.nearestPlanet = planets[0];
      nearestDistance = this.nearestPlanet.distance;
      _fn = function(planet) {
        var dist;
        dist = planet.distance;
        if (dist < nearestDistance) {
          _this.nearestPlanet = planet;
          return nearestDistance = dist;
        } else {

        }
      };
      for (_i = 0, _len = planets.length; _i < _len; _i++) {
        planet = planets[_i];
        _fn(planet);
      }
      return this.nearestPlanet;
    };

    Player.prototype.startJumping = function() {
      var cb,
        _this = this;
      this.jumping = true;
      this.jumpVelocity = this.minJump;
      cb = function() {
        _this.jumpVelocity = _this.jumpVelocity + 1 < _this.maxJump ? _this.jumpVelocity + 1 : _this.maxJump;
        if (_this.jumping) {
          return setTimeout(cb, 30);
        }
      };
      return cb();
    };

    Player.prototype.jump = function() {
      this.accel(window.rotation - Math.PI, this.jumpVelocity);
      this.jumping = false;
      return this.jumpVelocity = this.minJump;
    };

    Player.prototype.draw = function(s, g) {
      var angle, dist, x, y;
      this.s = s;
      this.g = g;
      x = this.x - this.g.offsetX;
      y = this.y - this.g.offsetY;
      angle = Math.atan2(x, y);
      dist = Math.sqrt((Math.pow(x, 2)) + (Math.pow(y, 2)));
      angle += this.g.rotation;
      x = (Math.cos(angle)) * dist;
      y = (Math.sin(angle)) * dist;
      x += this.g.w / 2;
      y += this.g.h / 2;
      return this.s.image(this.s[this.currentImage + "_" + this.direction], x - this.width - 2, y - this.height);
    };

    return Player;

  })();

  Galaxy = (function() {

    Galaxy.name = 'Galaxy';

    Galaxy.prototype.planets = [];

    Galaxy.prototype.offsetX = 0;

    Galaxy.prototype.offsetY = 0;

    Galaxy.prototype.w = 100;

    Galaxy.prototype.h = 100;

    Galaxy.prototype.rotation = 0;

    Galaxy.prototype.stars = false;

    function Galaxy(w, h, player, planets) {
      this.w = w;
      this.h = h;
      this.player = player;
      this.planets = planets;
    }

    Galaxy.prototype.draw = function(sketch) {
      var planet, _i, _len, _ref;
      this.sketch = sketch;
      this.drawStars();
      _ref = this.planets;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        planet = _ref[_i];
        this.drawPlanet(planet);
      }
      return this.player.draw(this.sketch, this, this.rotation);
    };

    Galaxy.prototype.drawPlanet = function(planet) {
      return planet.draw(this.sketch, this, this.rotation);
    };

    Galaxy.prototype.drawStars = function() {
      this.sketch.translate(this.w / 2, this.h / 2);
      this.sketch.rotate(this.rotation);
      this.sketch.image(this.sketch.stars, -500, -500);
      this.sketch.rotate(-this.rotation);
      return this.sketch.translate(-this.w / 2, -this.h / 2);
    };

    return Galaxy;

  })();

  Chrome = (function() {

    Chrome.name = 'Chrome';

    function Chrome(w, h) {
      this.w = w;
      this.h = h;
    }

    Chrome.prototype.barWidth = 200;

    Chrome.prototype.barHeight = 32;

    Chrome.prototype.barPadding = 4;

    Chrome.prototype.marginTop = 40;

    Chrome.prototype.marginBottom = 40;

    Chrome.prototype.marginLeft = 40;

    Chrome.prototype.marginRight = 40;

    Chrome.prototype.draw = function(s, player) {
      this.s = s;
      this.player = player;
      this.s.stroke(255);
      this.s.fill(0);
      this.s.rect(this.w - this.barWidth - this.marginRight, this.marginTop + 10, this.barWidth, this.barHeight);
      if (this.player.jumping) {
        this.s.noStroke();
        this.s.fill(255, 0, 0);
        this.s.rect(this.w - this.barWidth - this.marginRight + this.barPadding, this.marginTop + this.barPadding + 10, (this.barWidth - this.barPadding * 2) * (this.player.jumpVelocity - this.player.minJump) / (this.player.maxJump - this.player.minJump), this.barHeight - this.barPadding * 2);
      }
      return this.drawText("jump meter", this.w - this.barWidth - this.marginRight, this.marginTop);
    };

    Chrome.prototype.drawText = function(txt, x, y) {
      this.s.textFont(this.s.loadedFont, 15);
      this.s.fill(0);
      this.s.text(txt, x + 1.5, y + 1.5);
      this.s.text(txt, x + .5, y + 1.5);
      this.s.text(txt, x + 1.5, y + .5);
      this.s.fill(255);
      return this.s.text(txt, x + .5, y + .5);
    };

    return Chrome;

  })();

  w = 800;

  h = 480;

  rotation = 0;

  planets = [];

  planets.push(new Planet(0, 150, 100));

  planets.push(new Planet(300, -350, 60));

  planets.push(new Planet(-100, -450, 60));

  planets.push(new Planet(100, -700, 70));

  planets.push(new Planet(-100, -1000, 100));

  planets.push(new Sun(600, -600, 100));

  for (_i = 0, _len = planets.length; _i < _len; _i++) {
    planet = planets[_i];
    planet.setup();
  }

  player = new Player();

  player.y = -300;

  galaxy = new Galaxy(w, h, player, planets);

  chrome = new Chrome(w, h);

  window.player = player;

  window.galaxy = galaxy;

  KEY_UP = 38;

  KEY_DOWN = 40;

  KEY_LEFT = 37;

  KEY_RIGHT = 39;

  KEY_SPACE = 32;

  key_dir = -1;

  document.onkeyup = function(e) {
    if (key_dir === KEY_SPACE) {
      player.jump();
    }
    key_dir = -1;
    return player.walking = false;
  };

  document.onkeydown = function(e) {
    var cont;
    cont = false;
    switch (e.keyCode) {
      case KEY_UP:
        if (key_dir !== KEY_UP && 1 === 2) {
          key_dir = KEY_UP;
          player.accel(window.rotation - Math.PI, 10);
        }
        break;
      case KEY_DOWN:
        if (key_dir !== KEY_DOWN && 1 === 2) {
          key_dir = KEY_DOWN;
          player.accel(window.rotation, 10);
        }
        break;
      case KEY_LEFT:
        if (key_dir !== KEY_LEFT && player.onGround) {
          player.direction = player.DIR_LEFT;
          player.walking = true;
          player.accel(window.rotation - Math.PI / 2, 3, true);
        }
        break;
      case KEY_RIGHT:
        if (key_dir !== KEY_RIGHT && player.onGround) {
          player.direction = player.DIR_RIGHT;
          player.walking = true;
          player.accel(window.rotation + Math.PI / 2, 3, true);
        }
        break;
      case KEY_SPACE:
        if (key_dir !== KEY_SPACE && player.onGround) {
          key_dir = KEY_SPACE;
          player.startJumping();
        }
        break;
      default:
        cont = true;
    }
    if (!cont) {
      return e.preventDefault();
    }
  };

  setPixel = function(s, pixels, i) {
    pixels.setPixel(i, s.color(0));
    if (Math.random() * 1000 < 2) {
      return pixels.setPixel(i, s.color(255, 255, 255));
    }
  };

  sketch(function() {
    var _this = this;
    this.setup = function() {
      var dir, dirs, i, img, imgs, p, pixel, _j, _k, _l, _len1, _len2, _len3;
      _this.size(w, h);
      _this.background(0);
      _this.noFill();
      _this.frameRate(30);
      _this.loadedFont = _this.loadFont("fonts/Audiowide-Regular.ttf");
      imgs = [player.IMG_STANDING, player.IMG_WALKING, player.IMG_SQUATTING, player.IMG_FLYING];
      dirs = [player.DIR_LEFT, player.DIR_RIGHT];
      for (_j = 0, _len1 = imgs.length; _j < _len1; _j++) {
        img = imgs[_j];
        for (_k = 0, _len2 = dirs.length; _k < _len2; _k++) {
          dir = dirs[_k];
          _this[img + "_" + dir] = _this.loadImage("images/spiff/" + img + "_" + dir + ".png");
        }
      }
      _this.stars = _this.createImage(1000, 1000, _this.ARGB);
      p = _this.stars.pixels.toArray();
      for (i = _l = 0, _len3 = p.length; _l < _len3; i = ++_l) {
        pixel = p[i];
        setPixel(_this, _this.stars.pixels, i);
      }
      _this.stars.updatePixels();
      return _this;
    };
    return this.draw = function() {
      var diff, idealRotation, nearestPlanet;
      _this.background(0);
      nearestPlanet = player.findNearestPlanet(galaxy.planets, false);
      window.nearestPlanet = nearestPlanet;
      idealRotation = Math.PI / 2 - Math.atan2(nearestPlanet.x - player.x, nearestPlanet.y - player.y);
      diff = Math.abs(idealRotation - rotation);
      if ((Math.abs(idealRotation - Math.PI * 2 - rotation)) < diff) {
        idealRotation = idealRotation - Math.PI * 2;
      }
      if ((Math.abs(idealRotation + Math.PI * 2 - rotation)) < diff) {
        idealRotation = idealRotation + Math.PI * 2;
      }
      rotation += (idealRotation - rotation) * .1;
      if (rotation < 0) {
        rotation += Math.PI * 2;
      }
      rotation = rotation % (Math.PI * 2);
      window.rotation = rotation;
      galaxy.rotation = rotation;
      galaxy.offsetX += (player.x - galaxy.offsetX) * .3;
      galaxy.offsetY += (player.y - galaxy.offsetY) * .3;
      player.move().calculatePhysics(galaxy.planets);
      galaxy.draw(_this);
      return chrome.draw(_this, player);
    };
  });

}).call(this);
